services:
  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    user: ${DATABASE_USER}
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGPORT=${DATABASE_PORT}
    volumes:
      - invoice_postgres_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    profiles:
      - prod

  server:
    container_name: server
    image: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}
      - API_PORT=${API_PORT}
      - API_ALLOW_ORIGIN=${API_ALLOW_ORIGIN}
      - API_DEV_KEY=${API_DEV_KEY}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - database
    profiles:
      - prod

  client:
    container_name: client
    image: client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=https://${CLIENT_API_HOST}
    environment:
      - CLIENT_HOST=${CLIENT_HOST}
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - server
    profiles:
      - prod

  database.dev:
    container_name: database.dev
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    user: ${DATABASE_USER}
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGPORT=${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    profiles:
      - dev

  server.dev:
    container_name: server.dev
    image: server.dev
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./server
        target: /app
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}
      - API_PORT=${API_PORT}
      - API_ALLOW_ORIGIN=${API_ALLOW_ORIGIN}
      - API_DEV_KEY=${API_DEV_KEY}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - database.dev
    profiles:
      - dev

  client.dev:
    container_name: client.dev
    image: client.dev
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_BASE_URL=http://${CLIENT_API_HOST}:${API_PORT}
      - VITE_CLIENT_PORT=${CLIENT_PORT}
    volumes:
      - type: bind
        source: ./client
        target: /app
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - server.dev
    profiles:
      - dev

volumes:
  invoice_postgres_data:
    external: true
